# conda env create -f environment.yml
# mamba env create -f devel-env.yml
name: bmad-benchmarking
channels:
  - conda-forge
dependencies:
  - python=3.9
  - distgen
  - lume-impact
  - impact-t
  - bmad
  - pytao
  - jupyterlab
  - ipywidgets
  - pip
# Developer
#  - pip:
#    - git+git://github.com/some/repository
